### PR TITLE
Refactor constants into types for clarity's sake

### PR DESCRIPTION
**Pull request by campoy**
This PR creates types for the constants in the project in uses them to ensure the right values are being used in the right context.

This includes the types:

- Source
- SourceType
- ResourceName
- ResourceAlias
- AggregationLevel
- AggregationOperation

All of these types are of string kind and the constants are declared in groups with the intention of helping readers understand their structure.

### CODE REVIEW

**Comment by campoy** [comment]
Working on the rebase.

**Review by logicalhan — COMMENTED** [review]
/triage accepted
/assign @pwittrock

**Pull request merged**
